Repository MrSupiri/rancher-logging-pipeline-plumber, pull requests merged in 2021-08, with the labels that each got.

#53 automatically set the chart version to the release version
  charts/logging-pipeline-plumber/Chart.yaml
  scripts/build
  scripts/version
Labels: area/ci

#57 Fixed a routing issue with go embed
  Dockerfile
  charts/logging-pipeline-plumber/Chart.yaml
  pkg/webserver/handlers.go
  ui/src/App.jsx
  ui/src/components/FlowList.jsx
  ui/src/components/TestStatus.jsx
  ui/src/libs/useQuery.js
  ui/src/pages/DetailPage.jsx
Labels: area/ui

#58 Added a README
  README.md
Labels: area/documentation

#62 Fixed few issues with UI
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/manifest.json
  ui/src/App.jsx
  ui/src/pages/CreatePage.jsx
  ui/src/utils/flowtests/createFlowTest.js
Labels: area/ui

#63 Improved the quality of life of controller
  charts/logging-pipeline-plumber/templates/NOTES.txt
  charts/logging-pipeline-plumber/templates/role.yaml
  config/rbac/role.yaml
  controllers/cleanup.go
  controllers/flowtest_controller.go
  controllers/utils.go
  main.go
Labels: area/controller

#75 Completes test as soon as all test cases passes
  controllers/flowtest_controller.go
  controllers/utils.go
Labels: area/controller
